pod 'Masonry'
pod 'FreeStreamer', '~> 3.4.2'
pod 'AFNetworking', '~> 3.0'
pod 'YYModel', '~> 0.9.12'
pod 'SDWebImage', '~>3.7'
pod 'FMDB'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'YYCache', '~> 0.9.5'
pod 'HMSegmentedControl'
